### ISSUE TITLE
Workaround for Linux Mint 17.3

### ISSUE THREAD

**Issue by Lucie235** [marcoDallas/acpi_call_GUI#3]
Hi,

I'm running Linux Mint 17.3 and I'd really like to use acpi_call_GUI but cannot get around the error message that I have to install acpi_call_GUI_systemd but systemd is not yet implemented in LM 17.3 (ubuntu 14.04).
Even the command "sudo systemctl enable rc-local.service" is not available in LM17.3.
I could not find a another appropiate command to enable rc-local.service in LM 17.3.

Next I tried acpi_call_GUI-1.4.1 where I got stuck with the following error:

insmod: ERROR: could not load module /usr/local/bin/acpi_call/acpi_call.ko:
No such file or directory
/usr/local/bin/acpi_call_GUI/deactivate.sh: 38: 
/usr/local/bin/acpi_call_GUI/deactivate.sh: cannot create /proc/acpi/call: Directory nonexistent
cat: /proc/acpi/call: file or folder not found
Process Complete.

Indeed file /usr/local/bin/acpi_call/acpi_call.ko is not installed.

Is there any workaround that makes acipi_call_GUI usable for me?
Your suggestions will be appreciated very much.

**Comment by marcoDallas** [comment]
Hi @Lucie235 ,

Version 1.4.1 is quite outdated so I would not suggest to use it.

As far as I know [systemd is supported by Linux Mint 17.3 rosa](https://distrowatch.com/table.php?distribution=mint), as reported by the link, maybe it is not installed or activated, so you have to choose if you want to switch to systemd or do some steps to make this utility work.

For your convenience I will report here some instructions, remeber to make a system backup if you need, as there is always a risk of making the distribution to not boot.
### to replace sysV with systemd

1. Install [systemd-sysv](https://community.linuxmint.com/software/view/systemd-sysv) from the linux mint community;
2. Reboot;
3. To ensure everything is working run `systemctl status` in a terminal and see what it says;
4. Install and use the latest version of [acpi_call_GUI_systemd](https://github.com/marcoDallas/acpi_call_GUI_systemd);
5. Everything should be okay.

### to use sysV
You will have to manually download my fork of acpi_call in /usr/local/bin/acpi_call, make it, blacklist the video driver, insert the acpi_call module into the kernel and reboot.
Then you will need to install the version 1.4.1 of acpi_call_GUI and use in sequence only "change deactivation code" or "automatically find a deactivation code", "turn off discrete GPU" and then "automate disabling discrete GPU".

Let me know if you want to proceed this way and I will try to write a short guide as soon as I get some time.

**Comment by marcoDallas** [comment]
Closed because outdated
